# Generated by Django 4.0.4 on 2022-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_color_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='color',
            new_name='color1',
        ),
    ]
