# Generated by Django 4.0.4 on 2022-05-19 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_status_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
