# Generated by Django 4.0.4 on 2022-05-20 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_banner_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(default= 0 , on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
