# Generated by Django 4.0.4 on 2022-05-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1.Banner'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '3.Brand'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '4.Color'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '2.Product'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '5.Products Atribute'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.color'),
        ),
    ]
